INSERT INTO countries(code2, code3, name_en) VALUES('af','afg','Afghanistan');
INSERT INTO countries(code2, code3, name_en) VALUES('al','alb','Albania');
INSERT INTO countries(code2, code3, name_en) VALUES('dz','dza','Algeria');
INSERT INTO countries(code2, code3, name_en) VALUES('as','asm','American Samoa');
INSERT INTO countries(code2, code3, name_en) VALUES('ad','and','Andorra');
INSERT INTO countries(code2, code3, name_en) VALUES('ao','ago','Angola');
INSERT INTO countries(code2, code3, name_en) VALUES('ai','aia','Anguilla');
INSERT INTO countries(code2, code3, name_en) VALUES('aq','ata','Antarctica');
INSERT INTO countries(code2, code3, name_en) VALUES('ag','atg','Antigua and Barbuda');
INSERT INTO countries(code2, code3, name_en) VALUES('ar','arg','Argentina');
INSERT INTO countries(code2, code3, name_en) VALUES('am','arm','Armenia');
INSERT INTO countries(code2, code3, name_en) VALUES('aw','abw','Aruba');
INSERT INTO countries(code2, code3, name_en) VALUES('au','aus','Australia');
INSERT INTO countries(code2, code3, name_en) VALUES('at','aut','Austria');
INSERT INTO countries(code2, code3, name_en) VALUES('az','aze','Azerbaijan');
INSERT INTO countries(code2, code3, name_en) VALUES('bs','bhs','Bahamas');
INSERT INTO countries(code2, code3, name_en) VALUES('bh','bhr','Bahrain');
INSERT INTO countries(code2, code3, name_en) VALUES('bd','bgd','Bangladesh');
INSERT INTO countries(code2, code3, name_en) VALUES('bb','brb','Barbados');
INSERT INTO countries(code2, code3, name_en) VALUES('by','blr','Belarus');
INSERT INTO countries(code2, code3, name_en) VALUES('be','bel','Belgium');
INSERT INTO countries(code2, code3, name_en) VALUES('bz','blz','Belize');
INSERT INTO countries(code2, code3, name_en) VALUES('bj','ben','Benin');
INSERT INTO countries(code2, code3, name_en) VALUES('bm','bmu','Bermuda');
INSERT INTO countries(code2, code3, name_en) VALUES('bt','btn','Bhutan');
INSERT INTO countries(code2, code3, name_en) VALUES('bo','bol','Bolivia');
INSERT INTO countries(code2, code3, name_en) VALUES('ba','bih','Bosnia and Herzegovina');
INSERT INTO countries(code2, code3, name_en) VALUES('bw','bwa','Botswana');
INSERT INTO countries(code2, code3, name_en) VALUES('br','bra','Brazil');
INSERT INTO countries(code2, code3, name_en) VALUES('io','iot','British Indian Ocean Territory');
INSERT INTO countries(code2, code3, name_en) VALUES('vg','vgb','British Virgin Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('bn','brn','Brunei');
INSERT INTO countries(code2, code3, name_en) VALUES('bg','bgr','Bulgaria');
INSERT INTO countries(code2, code3, name_en) VALUES('bf','bfa','Burkina Faso');
INSERT INTO countries(code2, code3, name_en) VALUES('mm','mmr','Burma (Myanmar)');
INSERT INTO countries(code2, code3, name_en) VALUES('bi','bdi','Burundi');
INSERT INTO countries(code2, code3, name_en) VALUES('kh','khm','Cambodia');
INSERT INTO countries(code2, code3, name_en) VALUES('cm','cmr','Cameroon');
INSERT INTO countries(code2, code3, name_en) VALUES('ca','can','Canada');
INSERT INTO countries(code2, code3, name_en) VALUES('cv','cpv','Cape Verde');
INSERT INTO countries(code2, code3, name_en) VALUES('ky','cym','Cayman Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('cf','caf','Central African Republic');
INSERT INTO countries(code2, code3, name_en) VALUES('td','tcd','Chad');
INSERT INTO countries(code2, code3, name_en) VALUES('cl','chl','Chile');
INSERT INTO countries(code2, code3, name_en) VALUES('cn','chn','China');
INSERT INTO countries(code2, code3, name_en) VALUES('cx','cxr','Christmas Island');
INSERT INTO countries(code2, code3, name_en) VALUES('cc','cck','Cocos (Keeling) Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('co','col','Colombia');
INSERT INTO countries(code2, code3, name_en) VALUES('km','com','Comoros');
INSERT INTO countries(code2, code3, name_en) VALUES('cg','cog','Republic of the Congo');
INSERT INTO countries(code2, code3, name_en) VALUES('cd','cod','Democratic Republic of the Congo');
INSERT INTO countries(code2, code3, name_en) VALUES('ck','cok','Cook Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('cr','crc','Costa Rica');
INSERT INTO countries(code2, code3, name_en) VALUES('hr','hrv','Croatia');
INSERT INTO countries(code2, code3, name_en) VALUES('cu','cub','Cuba');
INSERT INTO countries(code2, code3, name_en) VALUES('cy','cyp','Cyprus');
INSERT INTO countries(code2, code3, name_en) VALUES('cz','cze','Czech Republic');
INSERT INTO countries(code2, code3, name_en) VALUES('dk','dnk','Denmark');
INSERT INTO countries(code2, code3, name_en) VALUES('dj','dji','Djibouti');
INSERT INTO countries(code2, code3, name_en) VALUES('dm','dma','Dominica');
INSERT INTO countries(code2, code3, name_en) VALUES('do','dom','Dominican Republic');
INSERT INTO countries(code2, code3, name_en) VALUES('tl','tls','Timor-Leste');
INSERT INTO countries(code2, code3, name_en) VALUES('ec','ecu','Ecuador');
INSERT INTO countries(code2, code3, name_en) VALUES('eg','egy','Egypt');
INSERT INTO countries(code2, code3, name_en) VALUES('sv','slv','El Salvador');
INSERT INTO countries(code2, code3, name_en) VALUES('gq','gnq','Equatorial Guinea');
INSERT INTO countries(code2, code3, name_en) VALUES('er','eri','Eritrea');
INSERT INTO countries(code2, code3, name_en) VALUES('ee','est','Estonia');
INSERT INTO countries(code2, code3, name_en) VALUES('et','eth','Ethiopia');
INSERT INTO countries(code2, code3, name_en) VALUES('fk','flk','Falkland Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('fo','fro','Faroe Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('fj','fji','Fiji');
INSERT INTO countries(code2, code3, name_en) VALUES('fi','fin','Finland');
INSERT INTO countries(code2, code3, name_en) VALUES('fr','fra','France');
INSERT INTO countries(code2, code3, name_en) VALUES('pf','pyf','French Polynesia');
INSERT INTO countries(code2, code3, name_en) VALUES('ga','gab','Gabon');
INSERT INTO countries(code2, code3, name_en) VALUES('gm','gmb','Gambia');
INSERT INTO countries(code2, code3, name_en) VALUES('ge','geo','Gaza Strip');
INSERT INTO countries(code2, code3, name_en) VALUES('de','deu','Germany');
INSERT INTO countries(code2, code3, name_en) VALUES('gh','gha','Ghana');
INSERT INTO countries(code2, code3, name_en) VALUES('gi','gib','Gibraltar');
INSERT INTO countries(code2, code3, name_en) VALUES('gr','grc','Greece');
INSERT INTO countries(code2, code3, name_en) VALUES('gl','grl','Greenland');
INSERT INTO countries(code2, code3, name_en) VALUES('gd','grd','Grenada');
INSERT INTO countries(code2, code3, name_en) VALUES('gu','gum','Guam');
INSERT INTO countries(code2, code3, name_en) VALUES('gt','gtm','Guatemala');
INSERT INTO countries(code2, code3, name_en) VALUES('gn','gin','Guinea');
INSERT INTO countries(code2, code3, name_en) VALUES('gw','gnb','Guinea-Bissau');
INSERT INTO countries(code2, code3, name_en) VALUES('gy','guy','Guyana');
INSERT INTO countries(code2, code3, name_en) VALUES('ht','hti','Haiti');
INSERT INTO countries(code2, code3, name_en) VALUES('hn','hnd','Honduras');
INSERT INTO countries(code2, code3, name_en) VALUES('hk','hkg','Hong Kong');
INSERT INTO countries(code2, code3, name_en) VALUES('hu','hun','Hungary');
INSERT INTO countries(code2, code3, name_en) VALUES('in','ind','Iceland');
INSERT INTO countries(code2, code3, name_en) VALUES('id','idn','Indonesia');
INSERT INTO countries(code2, code3, name_en) VALUES('ir','irn','Iran');
INSERT INTO countries(code2, code3, name_en) VALUES('iq','irq','Iraq');
INSERT INTO countries(code2, code3, name_en) VALUES('ie','irl','Ireland');
INSERT INTO countries(code2, code3, name_en) VALUES('im','imn','Isle of Man');
INSERT INTO countries(code2, code3, name_en) VALUES('il','isr','Israel');
INSERT INTO countries(code2, code3, name_en) VALUES('it','ita','Italy');
INSERT INTO countries(code2, code3, name_en) VALUES('ci','civ','Ivory Coast');
INSERT INTO countries(code2, code3, name_en) VALUES('jm','jam','Jamaica');
INSERT INTO countries(code2, code3, name_en) VALUES('jp','jpn','Japan');
INSERT INTO countries(code2, code3, name_en) VALUES('je','jey','Jersey');
INSERT INTO countries(code2, code3, name_en) VALUES('jo','jor','Jordan');
INSERT INTO countries(code2, code3, name_en) VALUES('kz','kaz','Kazakhstan');
INSERT INTO countries(code2, code3, name_en) VALUES('ke','ken','Kenya');
INSERT INTO countries(code2, code3, name_en) VALUES('ki','kir','Kiribati');
INSERT INTO countries(code2, code3, name_en) VALUES('kw','kwt','Kosovo');
INSERT INTO countries(code2, code3, name_en) VALUES('kg','kgz','Kyrgyzstan');
INSERT INTO countries(code2, code3, name_en) VALUES('la','lao','Laos');
INSERT INTO countries(code2, code3, name_en) VALUES('lv','lva','Latvia');
INSERT INTO countries(code2, code3, name_en) VALUES('lb','lbn','Lebanon');
INSERT INTO countries(code2, code3, name_en) VALUES('ls','lso','Lesotho');
INSERT INTO countries(code2, code3, name_en) VALUES('lr','lbr','Liberia');
INSERT INTO countries(code2, code3, name_en) VALUES('ly','lby','Libya');
INSERT INTO countries(code2, code3, name_en) VALUES('li','lie','Liechtenstein');
INSERT INTO countries(code2, code3, name_en) VALUES('lt','ltu','Lithuania');
INSERT INTO countries(code2, code3, name_en) VALUES('lu','lux','Luxembourg');
INSERT INTO countries(code2, code3, name_en) VALUES('mo','mac','Macau');
INSERT INTO countries(code2, code3, name_en) VALUES('mk','mkd','Macedonia');
INSERT INTO countries(code2, code3, name_en) VALUES('mg','mdg','Madagascar');
INSERT INTO countries(code2, code3, name_en) VALUES('mw','mwi','Malawi');
INSERT INTO countries(code2, code3, name_en) VALUES('my','mys','Malaysia');
INSERT INTO countries(code2, code3, name_en) VALUES('mv','mdv','Maldives');
INSERT INTO countries(code2, code3, name_en) VALUES('ml','mli','Mali');
INSERT INTO countries(code2, code3, name_en) VALUES('mt','mlt','Malta');
INSERT INTO countries(code2, code3, name_en) VALUES('mh','mhl','Marshall Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('mr','mrt','Mauritania');
INSERT INTO countries(code2, code3, name_en) VALUES('mu','mus','Mauritius');
INSERT INTO countries(code2, code3, name_en) VALUES('yt','myt','Mayotte');
INSERT INTO countries(code2, code3, name_en) VALUES('mx','mex','Mexico');
INSERT INTO countries(code2, code3, name_en) VALUES('fm','fsm','Micronesia');
INSERT INTO countries(code2, code3, name_en) VALUES('md','mda','Moldova');
INSERT INTO countries(code2, code3, name_en) VALUES('mc','mco','Monaco');
INSERT INTO countries(code2, code3, name_en) VALUES('mn','mng','Mongolia');
INSERT INTO countries(code2, code3, name_en) VALUES('me','mne','Montenegro');
INSERT INTO countries(code2, code3, name_en) VALUES('ms','msr','Montserrat');
INSERT INTO countries(code2, code3, name_en) VALUES('ma','mar','Morocco');
INSERT INTO countries(code2, code3, name_en) VALUES('mz','moz','Mozambique');
INSERT INTO countries(code2, code3, name_en) VALUES('na','nam','Namibia');
INSERT INTO countries(code2, code3, name_en) VALUES('nr','nru','Nauru');
INSERT INTO countries(code2, code3, name_en) VALUES('np','npl','Nepal');
INSERT INTO countries(code2, code3, name_en) VALUES('nl','nld','Netherlands');
INSERT INTO countries(code2, code3, name_en) VALUES('an','ant','Netherlands Antilles');
INSERT INTO countries(code2, code3, name_en) VALUES('nc','ncl','New Caledonia');
INSERT INTO countries(code2, code3, name_en) VALUES('nz','nzl','New Zealand');
INSERT INTO countries(code2, code3, name_en) VALUES('ni','nic','Nicaragua');
INSERT INTO countries(code2, code3, name_en) VALUES('ne','ner','Niger');
INSERT INTO countries(code2, code3, name_en) VALUES('ng','nga','Nigeria');
INSERT INTO countries(code2, code3, name_en) VALUES('nu','niu','Niue');
INSERT INTO countries(code2, code3, name_en) VALUES('mp','mnp','Norfolk Island');
INSERT INTO countries(code2, code3, name_en) VALUES('kp','prk','North Korea');
INSERT INTO countries(code2, code3, name_en) VALUES('no','nor','Norway');
INSERT INTO countries(code2, code3, name_en) VALUES('om','omn','Oman');
INSERT INTO countries(code2, code3, name_en) VALUES('pk','pak','Pakistan');
INSERT INTO countries(code2, code3, name_en) VALUES('pw','plw','Palau');
INSERT INTO countries(code2, code3, name_en) VALUES('pa','pan','Panama');
INSERT INTO countries(code2, code3, name_en) VALUES('pg','png','Papua New Guinea');
INSERT INTO countries(code2, code3, name_en) VALUES('py','pry','Paraguay');
INSERT INTO countries(code2, code3, name_en) VALUES('pe','per','Peru');
INSERT INTO countries(code2, code3, name_en) VALUES('ph','phl','Philippines');
INSERT INTO countries(code2, code3, name_en) VALUES('pn','pcn','Pitcairn Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('pl','pol','Poland');
INSERT INTO countries(code2, code3, name_en) VALUES('pt','prt','Portugal');
INSERT INTO countries(code2, code3, name_en) VALUES('pr','pri','Puerto Rico');
INSERT INTO countries(code2, code3, name_en) VALUES('qa','qat','Qatar');
INSERT INTO countries(code2, code3, name_en) VALUES('ro','rou','Romania');
INSERT INTO countries(code2, code3, name_en) VALUES('ru','rus','Russia');
INSERT INTO countries(code2, code3, name_en) VALUES('rw','rwa','Rwanda');
INSERT INTO countries(code2, code3, name_en) VALUES('bl','blm','Saint Barthelemy');
INSERT INTO countries(code2, code3, name_en) VALUES('ws','wsm','Samoa');
INSERT INTO countries(code2, code3, name_en) VALUES('sm','smr','San Marino');
INSERT INTO countries(code2, code3, name_en) VALUES('st','stp','Sao Tome and Principe');
INSERT INTO countries(code2, code3, name_en) VALUES('sa','sau','Saudi Arabia');
INSERT INTO countries(code2, code3, name_en) VALUES('sn','sen','Senegal');
INSERT INTO countries(code2, code3, name_en) VALUES('rs','srb','Serbia');
INSERT INTO countries(code2, code3, name_en) VALUES('sc','syc','Seychelles');
INSERT INTO countries(code2, code3, name_en) VALUES('sl','sle','Sierra Leone');
INSERT INTO countries(code2, code3, name_en) VALUES('sg','sgp','Singapore');
INSERT INTO countries(code2, code3, name_en) VALUES('sk','svk','Slovakia');
INSERT INTO countries(code2, code3, name_en) VALUES('si','svn','Slovenia');
INSERT INTO countries(code2, code3, name_en) VALUES('sb','slb','Solomon Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('so','som','Somalia');
INSERT INTO countries(code2, code3, name_en) VALUES('za','zaf','South Africa');
INSERT INTO countries(code2, code3, name_en) VALUES('kr','kor','South Korea');
INSERT INTO countries(code2, code3, name_en) VALUES('es','esp','Spain');
INSERT INTO countries(code2, code3, name_en) VALUES('lk','lka','Sri Lanka');
INSERT INTO countries(code2, code3, name_en) VALUES('sh','shn','Saint Helena');
INSERT INTO countries(code2, code3, name_en) VALUES('kn','kna','Saint Kitts and Nevis');
INSERT INTO countries(code2, code3, name_en) VALUES('lc','lca','Saint Lucia');
INSERT INTO countries(code2, code3, name_en) VALUES('mf','maf','Saint Martin');
INSERT INTO countries(code2, code3, name_en) VALUES('pm','spm','Saint Pierre and Miquelon');
INSERT INTO countries(code2, code3, name_en) VALUES('vc','vct','Saint Vincent and the Grenadines');
INSERT INTO countries(code2, code3, name_en) VALUES('sd','sdn','Sudan');
INSERT INTO countries(code2, code3, name_en) VALUES('sr','sur','Suriname_en');
INSERT INTO countries(code2, code3, name_en) VALUES('sj','sjm','Svalbard');
INSERT INTO countries(code2, code3, name_en) VALUES('sz','swz','Swaziland');
INSERT INTO countries(code2, code3, name_en) VALUES('se','swe','Sweden');
INSERT INTO countries(code2, code3, name_en) VALUES('ch','che','Switzerland');
INSERT INTO countries(code2, code3, name_en) VALUES('sy','syr','Syria');
INSERT INTO countries(code2, code3, name_en) VALUES('tw','twn','Taiwan');
INSERT INTO countries(code2, code3, name_en) VALUES('tj','tjk','Tajikistan');
INSERT INTO countries(code2, code3, name_en) VALUES('tz','tza','Tanzania');
INSERT INTO countries(code2, code3, name_en) VALUES('th','tha','Thailand');
INSERT INTO countries(code2, code3, name_en) VALUES('tg','tgo','Togo');
INSERT INTO countries(code2, code3, name_en) VALUES('tk','tkl','Tokelau');
INSERT INTO countries(code2, code3, name_en) VALUES('to','ton','Tonga');
INSERT INTO countries(code2, code3, name_en) VALUES('tt','tto','Trinidad and Tobago');
INSERT INTO countries(code2, code3, name_en) VALUES('tn','tun','Tunisia');
INSERT INTO countries(code2, code3, name_en) VALUES('tr','tur','Turkey');
INSERT INTO countries(code2, code3, name_en) VALUES('tm','tkm','Turkmenistan');
INSERT INTO countries(code2, code3, name_en) VALUES('tc','tca','Turks and Caicos Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('tv','tuv','Tuvalu');
INSERT INTO countries(code2, code3, name_en) VALUES('ae','are','United Arab Emirates');
INSERT INTO countries(code2, code3, name_en) VALUES('ug','uga','Uganda');
INSERT INTO countries(code2, code3, name_en) VALUES('gb','gbr','United Kingdom');
INSERT INTO countries(code2, code3, name_en) VALUES('ua','ukr','Ukraine');
INSERT INTO countries(code2, code3, name_en) VALUES('uy','ury','Uruguay');
INSERT INTO countries(code2, code3, name_en) VALUES('us','usa','United States');
INSERT INTO countries(code2, code3, name_en) VALUES('uz','uzb','Uzbekistan');
INSERT INTO countries(code2, code3, name_en) VALUES('vu','vut','Vanuatu');
INSERT INTO countries(code2, code3, name_en) VALUES('va','vat','Holy See (Vatican City)');
INSERT INTO countries(code2, code3, name_en) VALUES('ve','ven','Venezuela');
INSERT INTO countries(code2, code3, name_en) VALUES('vn','vnm','Vietnam');
INSERT INTO countries(code2, code3, name_en) VALUES('vi','vir','US Virgin Islands');
INSERT INTO countries(code2, code3, name_en) VALUES('wf','wlf','Wallis and Futuna');
INSERT INTO countries(code2, code3, name_en) VALUES('eh','esh','West Bank');
INSERT INTO countries(code2, code3, name_en) VALUES('ye','yem','Yemen');
INSERT INTO countries(code2, code3, name_en) VALUES('zm','zmb','Zambia');
INSERT INTO countries(code2, code3, name_en) VALUES('zw','zwe','Zimbabwe');